-- MySQL Script generated by MySQL Workbench
-- Пн 13 сен 2021 18:16:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MvpDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MvpDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MvpDB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `MvpDB` ;

-- -----------------------------------------------------
-- Table `MvpDB`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MvpDB`.`Accounts` (
  `idAccount` INT(11) NOT NULL AUTO_INCREMENT,
  `qrCode` VARCHAR(45) NULL DEFAULT NULL,
  `token` VARCHAR(45) NULL DEFAULT NULL,
  `accountActiveTime` DATE NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAccount`))
ENGINE = InnoDB
AUTO_INCREMENT = 175
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `MvpDB`.`News`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MvpDB`.`News` (
  `idNews` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `body` VARCHAR(245) NULL DEFAULT NULL,
  `imgPath` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idNews`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `MvpDB`.`ResetPassword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MvpDB`.`ResetPassword` (
  `idResetPassword` INT(11) NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(45) NULL DEFAULT NULL,
  `tmpPassword` VARCHAR(45) NULL DEFAULT NULL,
  `dateActiveToken` DATE NULL DEFAULT NULL,
  `idAccount` INT(11) NOT NULL,
  PRIMARY KEY (`idResetPassword`),
  INDEX `fk_ResetPassword_Accounts_idx` (`idAccount` ASC) VISIBLE,
  CONSTRAINT `fk_ResetPassword_Accounts`
    FOREIGN KEY (`idAccount`)
    REFERENCES `MvpDB`.`Accounts` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
